- name: "Install Minimal Software and Setup"
  hosts: localhost
  connection: local
  tasks:

    - name: Update Packages (Ubuntu)
      #      when: ansible_distibition == "Ubuntu"
      become: yes
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install Minimal Packages
      become: yes
      ansible.builtin.package:
        name:
          - sway
          - swaylock
          - swayidle
          # - waybar
          - wl-clipboard
          - slurp # Tools for screenshots
          - grim # Tools for screenshots
          - mpv
          - ffmpeg
          - fonts-font-awesome
          - hugo
          - foot
          # - network-manager
          - flatpak
        state: latest

    - name: Add the flathub flatpak repository remote
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        
    - name: Install Flatpak Packages
      community.general.flatpak:
        name:
          - io.gitlab.librewolf-community
